# A Minimal Docker Compose Example

version: "3.5"

networks:
  nw-useR:
    name: nw-useR

services:
  rstudio:
    image: scottcame/tidyverse-mariadb
    container_name: rstudio
    networks:
      - nw-useR
    ports:
      - 8787:8787
  mariadb:
    image: scottcame/demo-mariadb
    container_name: demo-mariadb
    networks:
      - nw-useR
